# Use a lighter version of Node as a parent image
FROM node:15.12.0

# Set the working directory to /client
WORKDIR /Client

ENV PATH /Client/node_modules/.bin:$PATH
# copy package.json into the container at /client

COPY package.json ./
COPY package-lock.json ./

RUN npm install



# add app
COPY . ./

# start app
CMD ["npm", "start"]
