version: '3.7'
services:
  nodejs-server:
    build:
      context: ./api
      dockerfile: Dockerfile.worker
    ports:
      - "8080:8080"
    container_name: node-api
    volumes:
       - ./api:/api

  react-ui:
    build:
      context: ./Client
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./Client:/Client
       - '/Client/node_modules'
